### ISSUE TITLE
Error with required module 'WebAdministrationDSC' version '2.7.0.0'

### ISSUE THREAD

**Issue by marcadamcarter** [microsoft/WebAdministrationDSC.Reverse#9]
https://github.com/microsoft/WebAdministrationDSC.Reverse/blob/942df22976afab43923de6119f21b13a76e511ec/Modules/WebAdministrationDSC.Reverse/WebAdministrationDSC.Reverse.psd1#L54

Was this requirement meant to be for **xWebAdministration** version 2.7.0.0 instead of **WebAdministrationDSC**?  I'm unable to locate anything higher than WebAdministrationDsc version 0.1.0.0
https://www.powershellgallery.com/packages/WebAdministrationDsc/0.1.0.0

Error: The required module 'WebAdministrationDSC' with version '2.7.0.0' is not loaded. Load the module or remove the module from 'RequiredModules' in the file 'C:\Program
Files\WindowsPowerShell\Modules\WebAdministrationDSC.Reverse\WebAdministrationDSC.Reverse.psd1'.

**Comment by NikCharlebois** [comment]
Hi Marc,

We are in the process of updating the tool into a module. Yes, you are right, it was meant for xWebAdministration 2.7.0.0 and not WebAdministrationDSC. Thanks

**Comment by marcadamcarter** [comment]
Hi Nik,
Thanks.  Saw you making changes earlier.  Sorry for jumping the gun on this.  We're in a documentation phase at work and I want to introduce ReverseDSC as a solution to that and as a doorway to DSC.

**Comment by NikCharlebois** [comment]
Let me know if there is anything we can help with. In the meantime, expect some major updates to the WebAdministration & SQL ReverseDSC modules over the next few weeks.
